### ISSUE TITLE
Unresolved reference: PLACE_ORDER

### ISSUE THREAD

**Issue by 8uu** [the-it-weirdo/Foodzzy#1]
the proplem in this code in file "CartActivity.kt"

    private fun networkRequest() {
        progressLayout.show()

        val jsonParams = JSONObject()
        jsonParams.put("user_id", userId)
        jsonParams.put("restaurant_id", restaurantId)
        jsonParams.put("total_cost", totalCost.toString())
        val foodIdArray = JSONArray()
        for (item in cartList) {
            val foodId = JSONObject()
            foodId.put("food_item_id", item.id)
            foodIdArray.put(foodId)
        }
        jsonParams.put("food", foodIdArray)

        NetworkTask(networkTaskListener).makeNetworkRequest(
            this@CartActivity, Request.Method.POST, PLACE_ORDER, jsonParams
        )
    }``

**Comment by the-it-weirdo** [comment]
Can you please describe the problem ?

**Comment by the-it-weirdo** [comment]
PLACE_ORDER is a constant defined in an untracked file. It is a sensitive API endpoint.  So, I am unable to disclose it.

All the network constants are:

const val NETWORK_IP = "API_URL_BASE"
const val REGISTER = "$NETWORK_IP/endpoint"
const val LOGIN = "$NETWORK_IP/endpoint"
const val FORGOT_PASSWORD = "$NETWORK_IP/endpoint"
const val RESET_PASSWORD = "$NETWORK_IP/endpoint"
const val FETCH_RESTAURANTS = "$NETWORK_IP/endpoint"
const val FETCH_RESTAURANT_DETAILS = "$NETWORK_IP/endpoint"
const val PLACE_ORDER = "$NETWORK_IP/endpoint"
const val FETCH_PREVIOUS_ORDERS = "$NETWORK_IP/endpoint"
const val TOKEN = "TOKEN_FOR_API_ACCESS"

**Comment by the-it-weirdo** [comment]
const val NETWORK_IP = "API_URL_BASE"
const val REGISTER = "$NETWORK_IP/endpoint"
const val LOGIN = "$NETWORK_IP/endpoint"
const val FORGOT_PASSWORD = "$NETWORK_IP/endpoint"
const val RESET_PASSWORD = "$NETWORK_IP/endpoint"
const val FETCH_RESTAURANTS = "$NETWORK_IP/endpoint"
const val FETCH_RESTAURANT_DETAILS = "$NETWORK_IP/endpoint"
const val PLACE_ORDER = "$NETWORK_IP/endpoint"
const val FETCH_PREVIOUS_ORDERS = "$NETWORK_IP/endpoint"
const val TOKEN = "TOKEN_FOR_API_ACCESS"

**Comment by isahilsb** [comment]
So how can i use your project ?? Is there any another way to open this project ?

**Comment by the-it-weirdo** [comment]
> So how can i use your project ?? Is there any another way to open this project ?

You can check the code for network APIs and endpoints given below. You will have to make a file or place these variables in someplace so that they are accessible throughout the app. You also have to change the values assigned in the variables to your own API endpoints. Depending on the API you are using, you might need to modify the JSON parsers and params code too. Do not change the name of the variables. Change only the values. If you change the name of the variables, you will need to find and change all references to that variable. ✌🏼 

```
const val NETWORK_IP = "API_URL_BASE"
const val REGISTER = "$NETWORK_IP/endpoint"
const val LOGIN = "$NETWORK_IP/endpoint"
const val FORGOT_PASSWORD = "$NETWORK_IP/endpoint"
const val RESET_PASSWORD = "$NETWORK_IP/endpoint"
const val FETCH_RESTAURANTS = "$NETWORK_IP/endpoint"
const val FETCH_RESTAURANT_DETAILS = "$NETWORK_IP/endpoint"
const val PLACE_ORDER = "$NETWORK_IP/endpoint"
const val FETCH_PREVIOUS_ORDERS = "$NETWORK_IP/endpoint"
const val TOKEN = "TOKEN_FOR_API_ACCESS"
```
